var intro_data = [
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Hey!",
        text:"Welcome to our Data Dealer Demo. You ready?",
        grfx:"img/intro/start2.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        hide_db:true
    },
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"This...",
        text:"is your database. Ready to be filled with millions of first-class data-sets.",
        grfx:"img/intro/sammle_profile.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        show_db:true
    },
    {
        view_id:'main_view',
        x:280,
        y:520,
        title:"Underworld",
        text:"For a little cash your sources will supply you with the good stuff: profile information.",
        grfx:"img/intro/schwarzmarkt_1.png",
        agents:['mannymayer'],
        contacts:['schwesterelfriede','stephanpetzold'],
        projects:[],
        customers:[]
    },
    {
        view_id:'main_view',
        x:180,
        y:480,
        title:"Gather Profiles",
        text:"Collect personal profiles and make sure your data lines stay busy.",
        grfx:"img/intro/kreislauf_1_schwarzmarkt.png",
        agents:['maraloft'],
        contacts:['onkelenzo'],
        projects:[],
        customers:[],
        contact_ready:['onkelenzo']
    },
    {
        view_id:'main_view',
        x:420,
        y:250,
        title:"Your Empire",
        text:"Create your own companies and online ventures.",
        grfx:"img/intro/projekte.png",
        agents:[],
        contacts:[],
        projects:['gewinnspiel','partnerboerse'],
        customers:[]
    },
    {
        view_id:'main_view',
        x:420,
        y:250,
        title:"Ventures",
        text:"Sweepstakes and online dating sites are ideal tools for amassing profiles.",
        grfx:"img/intro/kreislauf_2_imperium.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        project_ready:['gewinnspiel']
    },
    {
        view_id:'main_view',
        x:680,
        y:320,
        title:"Upgrade",
        text:"Upgrade your venture, advertise your products and grow your team.",
        grfx:"img/intro/ausbauen.png",
        agents:[],
        contacts:[],
        projects:['psychotest','vorteilsclub'],
        customers:[]
    },
    {
        view_id:'main_view',
        x:750,
        y:600,
        title:"Make Money",
        text:"Once you’ve amassed enough profiles, offer your database to interested companies for some much-needed cash.",
        grfx:"img/intro/kunden.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:['diebahn','krankenversicherung']
    },
    {
        view_id:'main_view',
        x:750,
        y:600,
        title:"Cash In",
        text:"Make great deals and watch the money roll in.",
        grfx:"img/intro/kreislauf_3_geld_machen.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:['mobilfunkdiskonter','centralsecurity']
    },
    {
        view_id:'db_view',
        x:480,
        y:320,
        title:"Let's take a peek...",
        text:"Your database is looking pretty well-stocked with profiles.",
        grfx:"img/intro/datenbank_innen.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    },
    {
        view_id:'db_view',
        x:480,
        y:320,
        title:"New profiles are waiting...",
        text:"Hint: Take a look at your database first and see what data needs bulking up.",
        grfx:"img/intro/get_ready.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    },
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Get Ready",
        text:"Any questions? Then check out the Help section. Fearless players jump right in!",
        grfx:"img/intro/start.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[]
    }
];

var levelup_data01 = [
    {
        view_id:'main_view',
        x:480,
        y:320,
        title:"Congrats!",
        text:"You just reached level 5.",
        grfx:"img/level_up.png",
        agents:[],
        contacts:[],
        projects:[],
        customers:[],
        noskip:true
    },
    {
        view_id:'main_view',
        x:480,
        y:120,
        title:"New Agent",
        text:"Quite ambitious, aren't you? Somehow or other, you've made a new acquaintance: Mr. Barnie Maddog knows everyone who's anyone in the country.",
        grfx:"img/level_up_krasser.png",
        agents:['ernstkrasser'],
        contacts:[],
        projects:[],
        customers:[],
        noskip:true
    },
    {
        view_id:'main_view',
        x:480,
        y:60,
        title:"New Sources",
        text:"To get things off to a good start, Barnie hands you two of his many contacts on a silver platter. Check them out immediately!",
        grfx:"img/level_up_kontakte.png",
        agents:[],
        contacts:['sieglindebayerwurtz','franzsauerzapf'],
        projects:[],
        customers:[],
        noskip:true
    }
];

var token_data = [
  {
    "x": 1000,
    "y": 539,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "nachname",
    "label": "Last Name",
    "title": "Last Name",
    "stats_text": "You know the last names of",
    "origin_stats_text": "You get the last names of",
    "description": "The last name is essential for the identification of a person. Combined with first name and date of birth, it’s pretty much a done deal. It’s not exactly a walk in the park, though, what with all those Smiths, Browns and Joneses.<br /><br />First name, last name and date of birth are among the key attributes in your database. Whenever you gain new profiles, your database might be able to use these attributes to connect them to existing profiles.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/nachname_s1.png",
    "sprite_img": "img/tokens/nachname_s1.png",
    "tokenset_img": "img/tokens/tokens_set/nachname_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/nachname-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/nachname-hover_s1.png",
    "sprite_img_down": "img/tokens/nachname-down_s1.png",
    "sprite_img_hover": "img/tokens/nachname-hover_s1.png",
    "sprite_img_drag": "img/tokens/nachname-drag_s1.png"
  },
  {
    "x": 766,
    "y": 532,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "adresse",
    "label": "Address",
    "title": "Address",
    "stats_text": "You know the street and house numbers of",
    "origin_stats_text": "You get the street and house numbers of",
    "description": "Knowing the address is perfect not only for spamming people with junk mail, but tells you lots of other things about them as well. Fancy neighborhood or ghetto? City slicker or country bumpkin? This information will prove essential in filing and pigeonholing. And just imagine the marketing possibilities!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/adresse_s1.png",
    "sprite_img": "img/tokens/adresse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/adresse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/adresse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/adresse-hover_s1.png",
    "sprite_img_down": "img/tokens/adresse-down_s1.png",
    "sprite_img_hover": "img/tokens/adresse-hover_s1.png",
    "sprite_img_drag": "img/tokens/adresse-drag_s1.png"
  },
  {
    "x": 893,
    "y": 622,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "wohnort",
    "label": "Postal Code",
    "title": "Postal Code",
    "stats_text": "You know the postal codes of",
    "origin_stats_text": "You get the postal codes of",
    "description": "Essential for precise identification, these codes created by the postal service will also tell you much, much more. Fancy neighborhood or ghetto? City slicker or country bumpkin? This information will prove essential in filing and pigeonholing. And just imagine the marketing possibilities!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/wohnort_s1.png",
    "sprite_img": "img/tokens/wohnort_s1.png",
    "tokenset_img": "img/tokens/tokens_set/wohnort_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/wohnort-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/wohnort-hover_s1.png",
    "sprite_img_down": "img/tokens/wohnort-down_s1.png",
    "sprite_img_hover": "img/tokens/wohnort-hover_s1.png",
    "sprite_img_drag": "img/tokens/wohnort-drag_s1.png"
  },
  {
    "x": 912,
    "y": 770,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "telefonnummer",
    "label": "Phone Number",
    "title": "Phone Number",
    "stats_text": "You know one or more phone numbers of",
    "origin_stats_text": "You get one or more phone numbers of",
    "description": "The phone is one of the most important personal communication tools. Marketing agencies pay good money for profiles that include phone numbers.<br /><br />Ever since the dawn of the age of smartphones, more and more personal information has been collected inside these constant companions. All that stored data can be made into near-perfect personality profiles. So extra-nasty data collectors plant funny apps on people’s phones which then sneakily tap the phones’ memory.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/telefonnummer_s1.png",
    "sprite_img": "img/tokens/telefonnummer_s1.png",
    "tokenset_img": "img/tokens/tokens_set/telefonnummer_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/telefonnummer-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/telefonnummer-hover_s1.png",
    "sprite_img_down": "img/tokens/telefonnummer-down_s1.png",
    "sprite_img_hover": "img/tokens/telefonnummer-hover_s1.png",
    "sprite_img_drag": "img/tokens/telefonnummer-drag_s1.png"
  },
  {
    "x": 782,
    "y": 673,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "geburtsdatum",
    "label": "Date of Birth",
    "title": "Date of Birth",
    "stats_text": "You know the date of birth of",
    "origin_stats_text": "You get the date of birth of",
    "description": "The combination of name and date of birth makes identifying a person a pretty safe bet. You can also learn someone’s age, and that in turn leads to lots of interesting conclusions. For example, concerning wealth, income, interests, problems, buying habits or state of health.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/geburtsdatum_s1.png",
    "sprite_img": "img/tokens/geburtsdatum_s1.png",
    "tokenset_img": "img/tokens/tokens_set/geburtsdatum_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/geburtsdatum-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/geburtsdatum-hover_s1.png",
    "sprite_img_down": "img/tokens/geburtsdatum-down_s1.png",
    "sprite_img_hover": "img/tokens/geburtsdatum-hover_s1.png",
    "sprite_img_drag": "img/tokens/geburtsdatum-drag_s1.png"
  },
  {
    "x": 1116,
    "y": 599,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "geschlecht",
    "label": "Sex",
    "title": "Sex",
    "stats_text": "You know the sex of",
    "origin_stats_text": "You get information about the sex of",
    "description": "The entry \"sex\" on birth certificates and in passports is thankfully less decisive in people's lives than it used to be. However, girls and boys are still fully under the thumb of their designated gender roles. Unequal incomes, interests, risk factors, medical needs, buying habits, life expectancy – knowing a person’s sex offers you countless opportunities.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/geschlecht_s1.png",
    "sprite_img": "img/tokens/geschlecht_s1.png",
    "tokenset_img": "img/tokens/tokens_set/geschlecht_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/geschlecht-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/geschlecht-hover_s1.png",
    "sprite_img_down": "img/tokens/geschlecht-down_s1.png",
    "sprite_img_hover": "img/tokens/geschlecht-hover_s1.png",
    "sprite_img_drag": "img/tokens/geschlecht-drag_s1.png"
  },
  {
    "x": 1018,
    "y": 696,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "email",
    "label": "Email",
    "title": "Email",
    "stats_text": "You know one or more email addresses of",
    "origin_stats_text": "You get one or more email addresses of",
    "description": "Nowadays email addresses have become more important than postal addresses. They’re the key to a net data gold mine. Countless online services utilize their users’ email address for registration instead of their name. And once you know someone’s email address, you can pinpoint them anywhere, no matter which nickname or pseudonym they use. In addition, email addresses can be sold quite profitably for marketing purposes.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/email_s1.png",
    "sprite_img": "img/tokens/email_s1.png",
    "tokenset_img": "img/tokens/tokens_set/email_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/email-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/email-hover_s1.png",
    "sprite_img_down": "img/tokens/email-down_s1.png",
    "sprite_img_hover": "img/tokens/email-hover_s1.png",
    "sprite_img_drag": "img/tokens/email-drag_s1.png"
  },
  {
    "x": 430,
    "y": 456,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "personalakten",
    "label": "Personnel\nrecords",
    "title": "Personnel records",
    "stats_text": "You know the personnel records of",
    "origin_stats_text": "You get the personnel records of",
    "description": "Always late? Prone to calling in \“sick\”? Whistle blower? Other red flags? Lots of companies keep fat files on their employees, including all their strengths, weaknesses and little lapses. Legal? More or less. But very interesting indeed for future employers.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/personalakten_s1.png",
    "sprite_img": "img/tokens/personalakten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/personalakten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/personalakten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/personalakten-hover_s1.png",
    "sprite_img_down": "img/tokens/personalakten-down_s1.png",
    "sprite_img_hover": "img/tokens/personalakten-hover_s1.png",
    "sprite_img_drag": "img/tokens/personalakten-drag_s1.png"
  },
  {
    "x": 464,
    "y": 618,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "lebenslauf",
    "label": "Resumé",
    "title": "Resumé",
    "stats_text": "You know about the education, jobs, unemployment and more of",
    "origin_stats_text": "You get information about the education, jobs, unemployment and more of",
    "description": "To get a decent job, a great CV is an absolute must. There should be no unexplained gaps, and any dallying on the path of life should be explained coherently. However, companies can’t simply trust the details given by jobseekers in application forms. There’s too much of a temptation for the applicants to fix things up a little.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/lebenslauf_s1.png",
    "sprite_img": "img/tokens/lebenslauf_s1.png",
    "tokenset_img": "img/tokens/tokens_set/lebenslauf_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/lebenslauf-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/lebenslauf-hover_s1.png",
    "sprite_img_down": "img/tokens/lebenslauf-down_s1.png",
    "sprite_img_hover": "img/tokens/lebenslauf-hover_s1.png",
    "sprite_img_drag": "img/tokens/lebenslauf-drag_s1.png"
  },
  {
    "x": 884,
    "y": 479,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "vorname",
    "label": "First Name",
    "title": "First Name",
    "stats_text": "You know the first names of",
    "origin_stats_text": "You get the first names of",
    "description": "Whether cool or dumb, common or unique, old-fashioned or trendy – the first name is essential for the definite identification of a person and thus one of the most important attributes for your business. The name can help you settle the question of gender as well. With a list of popular first names for several birth years you might even be able to guess the age of a person. Someone called Gertrude or Bob is most likely not younger than 40, on the other hand you probably won’t find a Kevin or Jennifer older than 50.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/vorname_s1.png",
    "sprite_img": "img/tokens/vorname_s1.png",
    "tokenset_img": "img/tokens/tokens_set/vorname_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/vorname-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/vorname-hover_s1.png",
    "sprite_img_down": "img/tokens/vorname-down_s1.png",
    "sprite_img_hover": "img/tokens/vorname-hover_s1.png",
    "sprite_img_drag": "img/tokens/vorname-drag_s1.png"
  },
  {
    "x": 601,
    "y": 651,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "besuchteschulen",
    "label": "Education",
    "title": "Education",
    "stats_text": "You know about the educations of",
    "origin_stats_text": "You get information about the educations of",
    "description": "Some celebs show off their bad report cards and dazzle the media with their youthful dropout antics. For those who are stars, a slacker past shouldn’t be too much of a problem. But cold, hard reality is somewhat different for most people. It’s especially important for young adults who want to get their foot in the door by boasting of their diligent careers at prestigious schools. Let’s hope none of them flunked \"Honesty in Application Writing\"...",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/besuchteschulen_s1.png",
    "sprite_img": "img/tokens/besuchteschulen_s1.png",
    "tokenset_img": "img/tokens/tokens_set/besuchteschulen_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/besuchteschulen-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/besuchteschulen-hover_s1.png",
    "sprite_img_down": "img/tokens/besuchteschulen-down_s1.png",
    "sprite_img_hover": "img/tokens/besuchteschulen-hover_s1.png",
    "sprite_img_drag": "img/tokens/besuchteschulen-drag_s1.png"
  },
  {
    "x": 839,
    "y": 298,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "einkommen",
    "label": "Income",
    "title": "Income",
    "stats_text": "You know the incomes of",
    "origin_stats_text": "You get information about the incomes of",
    "description": "Maximum wage earner, middle class or barely scraping by? Who cares whether it’s fair or not. There’s no question that there’s a huge difference in what people earn. It shapes their whole lives and the lives of their children too. Whether they earn a manager’s wage, are on the dole, live off a pension or receive financial support from their family – the financial situation of their customers is of interest to many corporations.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/einkommen_s1.png",
    "sprite_img": "img/tokens/einkommen_s1.png",
    "tokenset_img": "img/tokens/tokens_set/einkommen_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/einkommen-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/einkommen-hover_s1.png",
    "sprite_img_down": "img/tokens/einkommen-down_s1.png",
    "sprite_img_hover": "img/tokens/einkommen-hover_s1.png",
    "sprite_img_drag": "img/tokens/einkommen-drag_s1.png"
  },
  {
    "x": 685,
    "y": 257,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "schulden",
    "label": "Debt",
    "title": "Debt",
    "stats_text": "You know the financial status of",
    "origin_stats_text": "You learn the financial status of",
    "description": "Student loans, paying off the monthly payments for a swanky TV, leasing a car or a taking on a huge mortgage: a lot of people are in debt. Especially delicate if one loan only serves to pay off another. While this may be fine for governments and companies, for private persons it’s a real no-go. If your debt is out-of-control compared to income and purchases, you get blacklisted and no one wants to do business with you again. It’s especially interesting info for banks, mail-order companies, online shops and mobile phone providers.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/schulden_s1.png",
    "sprite_img": "img/tokens/schulden_s1.png",
    "tokenset_img": "img/tokens/tokens_set/schulden_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/schulden-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/schulden-hover_s1.png",
    "sprite_img_down": "img/tokens/schulden-down_s1.png",
    "sprite_img_hover": "img/tokens/schulden-hover_s1.png",
    "sprite_img_drag": "img/tokens/schulden-drag_s1.png"
  },
  {
    "x": 1168,
    "y": 445,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "konsumgewohnheiten",
    "label": "Buying Habits",
    "title": "Buying Habits",
    "stats_text": "You know the buying habits (brands, products, etc.) of",
    "origin_stats_text": "You get information about the buying habits (brands, products, etc.) of",
    "description": "Food, drinks, cosmetics, clothes, shoes, electronics, music, videos, books, magazines or cars: looking at a list of personal purchases over several months, you’ll learn quite a lot about the person concerned. Just from supermarket purchases alone you’ll be able to make a good guess whether someone is rich or poor, educated or not, and maybe even their sexual orientation. If you possess a large number of consumer profiles, your highly intelligent database can analyze them even better. Great stuff to sell – not just for targeted advertising.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/konsumgewohnheiten_s1.png",
    "sprite_img": "img/tokens/konsumgewohnheiten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/konsumgewohnheiten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/konsumgewohnheiten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/konsumgewohnheiten-hover_s1.png",
    "sprite_img_down": "img/tokens/konsumgewohnheiten-down_s1.png",
    "sprite_img_hover": "img/tokens/konsumgewohnheiten-hover_s1.png",
    "sprite_img_drag": "img/tokens/konsumgewohnheiten-drag_s1.png"
  },
  {
    "x": 1169,
    "y": 288,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "bevorzugtecomputergames",
    "label": "Preferred\nComputer Games",
    "title": "Preferred Computer Games",
    "stats_text": "You know the favorite computer games of",
    "origin_stats_text": "You get information about the favorite computer games of",
    "description": "Casual game, strategy, online role-playing game or blood-drenched shooter? Some people claim that the kind of games people prefer tells you something about their character. While the truth of the matter is still up for discussion, we’ll just let them believe what they want and give them what they need – in exchange for cold, hard cash.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/bevorzugtecomputergames_s1.png",
    "sprite_img": "img/tokens/bevorzugtecomputergames_s1.png",
    "tokenset_img": "img/tokens/tokens_set/bevorzugtecomputergames_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/bevorzugtecomputergames-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/bevorzugtecomputergames-hover_s1.png",
    "sprite_img_down": "img/tokens/bevorzugtecomputergames-down_s1.png",
    "sprite_img_hover": "img/tokens/bevorzugtecomputergames-hover_s1.png",
    "sprite_img_drag": "img/tokens/bevorzugtecomputergames-drag_s1.png"
  },
  {
    "x": 686,
    "y": 402,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "gewicht",
    "label": "Weight",
    "title": "Weight",
    "stats_text": "You know the current weights of",
    "origin_stats_text": "You get the current weights of",
    "description": "Anorexic, obese or just right? Sorry folks: those who deviate from the norm often find themselves unwanted as customers. Weight is lucrative information for every client dealing in health. Some employers are also not averse to knowing it, either. And let’s not even get started on advertising targeted for weight loss!",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/gewicht_s1.png",
    "sprite_img": "img/tokens/gewicht_s1.png",
    "tokenset_img": "img/tokens/tokens_set/gewicht_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/gewicht-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/gewicht-hover_s1.png",
    "sprite_img_down": "img/tokens/gewicht-down_s1.png",
    "sprite_img_hover": "img/tokens/gewicht-hover_s1.png",
    "sprite_img_drag": "img/tokens/gewicht-drag_s1.png"
  },
  {
    "x": 572,
    "y": 489,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "koerpergroesse",
    "label": "Height",
    "title": "Height",
    "stats_text": "You know the heights of ",
    "origin_stats_text": "You get the heights of ",
    "description": "Mainly useful when combined with weight. Once you have both, you can calculate the body mass index, or BMI for short. This is much more useful than weight alone and can be sold for even more money. Fat people have no chance at certain jobs and health insurance can also do without potential high-risk patients.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/koerpergroesse_s1.png",
    "sprite_img": "img/tokens/koerpergroesse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/koerpergroesse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/koerpergroesse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/koerpergroesse-hover_s1.png",
    "sprite_img_down": "img/tokens/koerpergroesse-down_s1.png",
    "sprite_img_hover": "img/tokens/koerpergroesse-hover_s1.png",
    "sprite_img_drag": "img/tokens/koerpergroesse-drag_s1.png"
  },
  {
    "x": 1015,
    "y": 308,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "ernaehrungsweise",
    "label": "Diet",
    "title": "Diet",
    "stats_text": "You know the daily diet of",
    "origin_stats_text": "You get the daily diet of",
    "description": "Mounds of meat or mainly vegetarian? Chips, coke and a daily dose of frozen food, or organic, light and lots of veggies? Using a list of purchases, you can create nice diet profiles, and from those you can in turn conclude something about people’s health status, even make some predictions for the future. The time period covered doesn’t even have to be that long - a few weeks will usually suffice.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/ernaehrungsweise_s1.png",
    "sprite_img": "img/tokens/ernaehrungsweise_s1.png",
    "tokenset_img": "img/tokens/tokens_set/ernaehrungsweise_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/ernaehrungsweise-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/ernaehrungsweise-hover_s1.png",
    "sprite_img_down": "img/tokens/ernaehrungsweise-down_s1.png",
    "sprite_img_hover": "img/tokens/ernaehrungsweise-hover_s1.png",
    "sprite_img_drag": "img/tokens/ernaehrungsweise-drag_s1.png"
  },
  {
    "x": 726,
    "y": 820,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "krankenakte",
    "label": "Medical Records",
    "title": "Medical Records",
    "stats_text": "You have the detailed medical records of",
    "origin_stats_text": "You get the detailed medical records of",
    "description": "Past and current ailments, treatments and operations, examination results and their exact date: the medical records produced in doctors’ offices and hospitals offer important clues for future prognoses. The health industry pays good money for information like this.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/krankenakte_s1.png",
    "sprite_img": "img/tokens/krankenakte_s1.png",
    "tokenset_img": "img/tokens/tokens_set/krankenakte_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/krankenakte-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/krankenakte-hover_s1.png",
    "sprite_img_down": "img/tokens/krankenakte-down_s1.png",
    "sprite_img_hover": "img/tokens/krankenakte-hover_s1.png",
    "sprite_img_drag": "img/tokens/krankenakte-drag_s1.png"
  },
  {
    "x": 874,
    "y": 936,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "chronischekrankheiten",
    "label": "Chronic\nIllnesses",
    "title": "Chronic Illnesses",
    "stats_text": "You know about the chronic ailments (or their absence) of",
    "origin_stats_text": "You get information about the chronic ailments (or their absence) of",
    "description": "Asthma, migraines, allergies, eczema or chronic back problems? Drug addiction, depression, hepatitis or the heavy stuff like multiple sclerosis or cancer? Insurance companies are dying to know about these things, and certain employers wouldn’t be averse to getting this info either.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/chronischekrankheiten_s1.png",
    "sprite_img": "img/tokens/chronischekrankheiten_s1.png",
    "tokenset_img": "img/tokens/tokens_set/chronischekrankheiten_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/chronischekrankheiten-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/chronischekrankheiten-hover_s1.png",
    "sprite_img_down": "img/tokens/chronischekrankheiten-down_s1.png",
    "sprite_img_hover": "img/tokens/chronischekrankheiten-hover_s1.png",
    "sprite_img_drag": "img/tokens/chronischekrankheiten-drag_s1.png"
  },
  {
    "x": 1039,
    "y": 921,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "anzahldersolarienbesuche",
    "label": "Tanning Booth\nVisits",
    "title": "Tanning Booth Visits",
    "stats_text": "You know the UV exposure of",
    "origin_stats_text": "You get information about the UV exposure of",
    "description": "A weekly dose of twenty minutes of artificial sun inside the strongest ray gun available? Just don’t tell your dermatologist! Making a habit of this can’t be good – some day one of those moles might take action and grow up to be a gnarly melanoma. Those concerned will find out sooner or later, but there’s many more people interested in the casual handling of UV radiation. After all, to the health industry the world is nothing but a long list of risk factors.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/anzahldersolarienbesuche_s1.png",
    "sprite_img": "img/tokens/anzahldersolarienbesuche_s1.png",
    "tokenset_img": "img/tokens/tokens_set/anzahldersolarienbesuche_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/anzahldersolarienbesuche-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/anzahldersolarienbesuche-hover_s1.png",
    "sprite_img_down": "img/tokens/anzahldersolarienbesuche-down_s1.png",
    "sprite_img_hover": "img/tokens/anzahldersolarienbesuche-hover_s1.png",
    "sprite_img_drag": "img/tokens/anzahldersolarienbesuche-drag_s1.png"
  },
  {
    "x": 1389,
    "y": 622,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "alterbeimerstenmal",
    "label": "Age at first\nsexual encounter",
    "title": "Age at first sexual encounter",
    "stats_text": "You know the age they were when they shagged the first time for",
    "origin_stats_text": "You learn the age they were when they shagged the first time for",
    "description": "Now isn’t this a juicy little detail? And quite useful for your personality profiles. Lost their virginity too early? Probably prone to rash decisions and easily manipulated! Much too late? Weirdo! From the \“reliable psychological matching test\“ offered at your online dating portal you learn even more than that. Isn’t it great how people don’t bother to read your privacy policy?",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/alterbeimerstenmal_s1.png",
    "sprite_img": "img/tokens/alterbeimerstenmal_s1.png",
    "tokenset_img": "img/tokens/tokens_set/alterbeimerstenmal_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/alterbeimerstenmal-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/alterbeimerstenmal-hover_s1.png",
    "sprite_img_down": "img/tokens/alterbeimerstenmal-down_s1.png",
    "sprite_img_hover": "img/tokens/alterbeimerstenmal-hover_s1.png",
    "sprite_img_drag": "img/tokens/alterbeimerstenmal-drag_s1.png"
  },
  {
    "x": 1222,
    "y": 737,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "sexuelleorientierung",
    "label": "Sexual\nOrientation",
    "title": "Sexual Orientation",
    "stats_text": "You know the sexual orientation of",
    "origin_stats_text": "You learn the sexual orientation of",
    "description": "Life’s not as hard as it used to be if you’re gay. However, there’s still plenty of Neanderthals out there who can’t deal with certain sexual orientations. For this reason, some people hide their orientation from their family or their employer. But not from you! Sexual orientation can be used for target group specific advertising – and, in the end, no profile is complete without it.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/sexuelleorientierung_s1.png",
    "sprite_img": "img/tokens/sexuelleorientierung_s1.png",
    "tokenset_img": "img/tokens/tokens_set/sexuelleorientierung_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/sexuelleorientierung-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/sexuelleorientierung-hover_s1.png",
    "sprite_img_down": "img/tokens/sexuelleorientierung-down_s1.png",
    "sprite_img_hover": "img/tokens/sexuelleorientierung-hover_s1.png",
    "sprite_img_drag": "img/tokens/sexuelleorientierung-drag_s1.png"
  },
  {
    "x": 1266,
    "y": 592,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "beziehungsstatus",
    "label": "Relationship\nStatus",
    "title": "Relationship Status",
    "stats_text": "You know how complicated things are for",
    "origin_stats_text": "You learn how complicated things are for",
    "description": "Single, shacked up, married, divorced, widowed, other? Singles are generally more flexible, couples more stable. Nowadays this can change pretty fast, but it can still be made use of – for advertising and for creating comprehensive personality profiles.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/beziehungsstatus_s1.png",
    "sprite_img": "img/tokens/beziehungsstatus_s1.png",
    "tokenset_img": "img/tokens/tokens_set/beziehungsstatus_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/beziehungsstatus-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/beziehungsstatus-hover_s1.png",
    "sprite_img_down": "img/tokens/beziehungsstatus-down_s1.png",
    "sprite_img_hover": "img/tokens/beziehungsstatus-hover_s1.png",
    "sprite_img_drag": "img/tokens/beziehungsstatus-drag_s1.png"
  },
  {
    "x": 1318,
    "y": 923,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "partyfotos",
    "label": "Party Photos",
    "title": "Party Photos",
    "stats_text": "You have funny party pictures of",
    "origin_stats_text": "You get funny party pictures of",
    "description": "People are so cute. Especially teenagers. Just look how much they enjoy taking strange pictures and putting them out there for anyone to see. Each and every funny pic is immediately put online, and if the posers are not doing it themselves, their esteemed friends or the party photo portal’s photographer will take care of it. Of course not every employer is bothered by pictures of their half-naked, screaming alcohol-infused employee from that party last month. But they definitely want to take a look.",
    "is_num": true,
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/partyfotos_s1.png",
    "sprite_img": "img/tokens/partyfotos_s1.png",
    "tokenset_img": "img/tokens/tokens_set/partyfotos_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/partyfotos-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/partyfotos-hover_s1.png",
    "sprite_img_down": "img/tokens/partyfotos-down_s1.png",
    "sprite_img_hover": "img/tokens/partyfotos-hover_s1.png",
    "sprite_img_drag": "img/tokens/partyfotos-drag_s1.png"
  },
  {
    "x": 413,
    "y": 807,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "vertrauenswuerdigoderunzuverlaessig",
    "label": "Trustworthy/\nUnreliable?",
    "title": "Trustworthy or Unreliable?",
    "stats_text": "You know the loyalty and reliability of",
    "origin_stats_text": "You get information about the loyalty and reliability of",
    "description": "Can this person be relied upon or are we dealing with a real flake? It’s a question countless employers undoubtedly ask themselves during job interviews. There’s only so much time for those talks, and a more reliable assessment would be great. Little tricks like online personality tests can help out. There might be a considerable margin of error, but better than nothing, right?",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "sprite_img": "img/tokens/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "tokenset_img": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/vertrauenswuerdigoderunzuverlaessig-hover_s1.png",
    "sprite_img_down": "img/tokens/vertrauenswuerdigoderunzuverlaessig-down_s1.png",
    "sprite_img_hover": "img/tokens/vertrauenswuerdigoderunzuverlaessig-hover_s1.png",
    "sprite_img_drag": "img/tokens/vertrauenswuerdigoderunzuverlaessig-drag_s1.png"
  },
  {
    "x": 539,
    "y": 781,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "zufriedenoderfrustriert",
    "label": "Happy/\nFrustrated?",
    "title": "Happy or Frustrated?",
    "stats_text": "You know the happiness level of",
    "origin_stats_text": "You get information about the happiness level of",
    "description": "Generally quite happy? Or discontent and frustrated? There are many ways to scan a person’s psychological wiring. Just don’t spring it on them or you will learn nothing. If you go at it with a little more finesse and trickery, people will happily let you into their confidence. Character assessments like these are a great basis for an informed analysis of a person.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/zufriedenoderfrustriert_s1.png",
    "sprite_img": "img/tokens/zufriedenoderfrustriert_s1.png",
    "tokenset_img": "img/tokens/tokens_set/zufriedenoderfrustriert_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/zufriedenoderfrustriert-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/zufriedenoderfrustriert-hover_s1.png",
    "sprite_img_down": "img/tokens/zufriedenoderfrustriert-down_s1.png",
    "sprite_img_hover": "img/tokens/zufriedenoderfrustriert-hover_s1.png",
    "sprite_img_drag": "img/tokens/zufriedenoderfrustriert-drag_s1.png"
  },
  {
    "x": 561,
    "y": 924,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "iq",
    "label": "IQ",
    "title": "IQ",
    "stats_text": "You know the so-called IQ of",
    "origin_stats_text": "You get the so-called IQ of",
    "description": "Should IQ really be used to measure intelligence? Psychologists have been debating the issue for decades now. Despite all that, people still love those IQ tests with undamped fervor, and no employer would turn down test results of this sort. Just to make sure...",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/iq_s1.png",
    "sprite_img": "img/tokens/iq_s1.png",
    "tokenset_img": "img/tokens/tokens_set/iq_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/iq-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/iq-hover_s1.png",
    "sprite_img_down": "img/tokens/iq-down_s1.png",
    "sprite_img_hover": "img/tokens/iq-hover_s1.png",
    "sprite_img_drag": "img/tokens/iq-drag_s1.png"
  },
  {
    "x": 1377,
    "y": 778,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "passwoerter",
    "label": "Passwords",
    "title": "Passwords",
    "stats_text": "You know one or more passwords of",
    "origin_stats_text": "You learn one or more passwords of",
    "description": "Other people’s passwords in your database? Getting into sketchy territory, aren’t we? But who knows, you might be able to use them someday. Let’s hang on to them, \"just in case\". You might just be able to recognize users of certain web portals even though they use a pseudonym or an anonymous email address.<br /><br />And should you ever be really desperate for cash, there are always certain dark corners of the data market with some interest in delicate matters like this...",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/passwoerter_s1.png",
    "sprite_img": "img/tokens/passwoerter_s1.png",
    "tokenset_img": "img/tokens/tokens_set/passwoerter_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/passwoerter-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/passwoerter-hover_s1.png",
    "sprite_img_down": "img/tokens/passwoerter-down_s1.png",
    "sprite_img_hover": "img/tokens/passwoerter-hover_s1.png",
    "sprite_img_drag": "img/tokens/passwoerter-drag_s1.png"
  },
  {
    "x": 522,
    "y": 326,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "kreditkartennummer",
    "label": "Credit Card\nNumber",
    "title": "Credit Card Number",
    "stats_text": "You know the credit card numbers of",
    "origin_stats_text": "You get the credit card numbers of",
    "description": "Credit cards are GREAT. As soon as this beloved online payment method enters the game, you’ve won. You’ll find some pretty reliable personal data, never mind the flourishing illegal trade in credit card numbers. However, you should think thrice before you get involved in this...",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/kreditkartennummer_s1.png",
    "sprite_img": "img/tokens/kreditkartennummer_s1.png",
    "tokenset_img": "img/tokens/tokens_set/kreditkartennummer_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/kreditkartennummer-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/kreditkartennummer-hover_s1.png",
    "sprite_img_down": "img/tokens/kreditkartennummer-down_s1.png",
    "sprite_img_hover": "img/tokens/kreditkartennummer-hover_s1.png",
    "sprite_img_drag": "img/tokens/kreditkartennummer-drag_s1.png"
  },
  {
    "x": 1192,
    "y": 878,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "ipadresse",
    "label": "IP Address",
    "title": "IP Address",
    "stats_text": "You know one or more IP addresses of",
    "origin_stats_text": "You get one or more IP addresses of",
    "description": "Computer, game console or smartphone – every device connected to the web has its own IP address. Users leave their tracks everywhere, even when surfing the net without being logged in anywhere.<br /><br />IP addresses might be shared among several members of a household, but a decent collection still constitutes an important foundation for your database – using these, you’ll be able to make some intelligent connections and links between several data sets.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/ipadresse_s1.png",
    "sprite_img": "img/tokens/ipadresse_s1.png",
    "tokenset_img": "img/tokens/tokens_set/ipadresse_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/ipadresse-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/ipadresse-hover_s1.png",
    "sprite_img_down": "img/tokens/ipadresse-down_s1.png",
    "sprite_img_hover": "img/tokens/ipadresse-hover_s1.png",
    "sprite_img_drag": "img/tokens/ipadresse-drag_s1.png"
  },
  {
    "x": 1319,
    "y": 453,
    "font_attr": {
      "font": "12px Bowlby",
      "fill": "#010",
      "opacity": 0.5
    },
    "token_id": "politischeeinstellung",
    "label": "Political\nAttitudes",
    "title": "Political Attitudes",
    "stats_text": "You have clues to the political attitudes of",
    "origin_stats_text": "You get clues to the political attitudes of",
    "description": "Liberal or conservative? Left or right? Indifferent or dedicated? Political attitude is key for many people and an essential part of a balanced personality profile.<br /><br />Even though really nasty governmental snooping à la KGB is a thing of the past in these parts (we hope!) – any security agency would surely appreciate a list of bothersome, critical or even \"radical\" names.",
    "sprite_w": 118,
    "sprite_h": 118,
    "logo": "img/tokens/tokens_logo/politischeeinstellung_s1.png",
    "sprite_img": "img/tokens/politischeeinstellung_s1.png",
    "tokenset_img": "img/tokens/tokens_set/politischeeinstellung_s1.png",
    "tokenset_img_down": "img/tokens/tokens_set/politischeeinstellung-down_s1.png",
    "tokenset_img_up": "img/tokens/tokens_set/politischeeinstellung-hover_s1.png",
    "sprite_img_down": "img/tokens/politischeeinstellung-down_s1.png",
    "sprite_img_hover": "img/tokens/politischeeinstellung-hover_s1.png",
    "sprite_img_drag": "img/tokens/politischeeinstellung-drag_s1.png"
  }
];
